src/streamsync/app_runner.py, tests/test_app_runner.py
solve #137 
This PR implements support for the python debugger. This allows you to add a breakpoint in the code and explore the running context.
I didn't have to introduce new tests. There was already a test that cover
The file name appears in error messages when the user changes the python code and breaks it.
=> compile python user code before running it to allow interactive debugging

src/streamsync/serve.py, tests/test_serve.py
Force the mimetype of javascript files exposed in the content-type attribute of http requests for servers on poorly configured Windows
fix #108
=> force javascript mimetype when it is not valid

docs/docs/frontend-scripts.md, ui/src/core_components/CoreRoot.vue
```python
initial_state = ss.init_state({
"my_app": {
"title": "My App"
},
})
initial_state.import_stylesheet("reset-css", "https://cdn.jsdelivr.net/npm/reset-css@5.0.2/reset.min.css")
initial_state.import_stylesheet("theme", "/static/main.css")
initial_state.import_script('tailwind', "https://cdn.tailwindcss.com")
```
=> load stylesheet and javascript script from remote location

src/streamsync/core.py, tests/test_core.py
solve the issue [Large plotly plots will crash streamsync, while dash has no issues showing the same...](https://github.com/streamsync-cloud/streamsync/issues/190)
---
Python's default serializer is very greedy on a plotly object. It is difficult to render a visualization of more than 5000 elements.
Plotly implements its own serializer using orjson. This is what should be used in streamsync.
=> Support huge plotly plots on streamsync

ui/src/core_components/CoreDataframe.vue
The fix has been designed by @thondeboer. It's describe in [https://github.com/streamsync-cloud/streamsync/issues/188](https://github.com/streamsync-cloud/streamsync/issues/188)
---
I have triggered the bug on `ubuntu / firefox 120.0.1 (64-bit)`. The test case was working fine on `ubuntu / chromium 112.0.5615.49` with streamsync 0.2.8
=> Off-by-one issue in the DataFrame - Last line is not shown in dataframe component on firefox

apps/hello/main.py, apps/hello/ui.json, src/streamsync/app_templates/hello/main.py, src/streamsync/app_templates/hello/ui.json, ui/src/core/templateMap.ts, ui/src/core_components/CorePagination.vue
This PR implements a Pagination component. This component allows to split a dataframe or repeater into several pages if it's too large. Pagination is a robust solution for displaying dataframes of several thousands rows.
I've documented its usage on ``hello`` app.
* user can change page
* user goes to previous page / to next page
* user can change the number of elements per page (optional)
* the user can go to a specific page (optional)
* the developer associates the number of records with a server state
* the developer associates the number of records per page with a server state (optional)
* the developer can enable fast movement to a specific page
* the developer can suggest to the user to change the number of pages
* the developer subscribes a page change to a backend event
* the …
=> pagination component for repeater and dataframe

src/streamsync/core.py
when state is changed concurrently. Suggested mitigation: construct a list of the items first, and then iterate. A safer solution would be to make a lock around constructing the list, but that's more work due to the recursive construction in StateProxy. list(...) is not atomic in Python and the iterator could change while constructing the list. In practice, this change fixed the problem for me.
```
Traceback (most recent call last):
File "/app/venv/lib/python3.11/site-packages/streamsync/app_runner.py", line 191, in _handle_state_enquiry
mutations = session.session_state.user_state.get_mutations_as_dict()
File "/app/venv/lib/python3.11/site-packages/streamsync/core.py", line 232, in get_mutations_as_dict for key, value in self.state.items():
RuntimeError: dictionary changed size during …
```
=> Data race in StateProxy.state

src/streamsync/core.py
Corrected the use of escaped keys in serializing StateProxy mutations. Replaced instance where unescaped key was used, ensuring consistency and correct handling of keys with dots.
=> Fix: Use escaped keys in StateProxy serialization

tests/test_core.py
`Adding a class method to count initial mutations for a StateProxy. Checking the amount of mutations per each step of the test to ensure that mutations are properly tracked.`
In regards to our prior discussion with @ramedina86, I found that the most reliable way to avoid issues like #198 in the future is to consistently track how many mutations are produced by the `get_mutations_as_dict` method in `StateProxy`, and compare the amount to the "ground truth" (i.e. actual number of mutations, which is easily deductible). I updated the mutation test to do exactly that. A method that counts expected "initial mutations" was also added, to make the test independent from the state of the dictionary initially passed to `TestStateProxy`.
I will be considering designing other tests as well, and any …
=> Expanding mutation test

src/streamsync/core.py, tests/test_app_runner.py, tests/test_core.py, ui/src/core/index.ts
Providing `__delitem__` method for `StateProxy` and `StreamsyncState`, and dict-like `remove()` API referencing the same method. Adding a "-" prefix for state keys meant to be removed at the frontend side when applying for mutated set of `StateProxy`. Enabling frontend to distinguish deletion mutations in `ingestMutations` function of `core/index.ts`.
=> Enabling deletion mutations

tests/test_core.py
As discussed, this actually produces two mutations rather than one. I must've overlooked it when submitting, my apologies.
=> Minor fix for test_mutations

src/streamsync/core.py
Escaping existing '\' character with another one, to disable SyntaxWarning.
=> Fix for escape sequence

tests/test_app_runner.py
Looks quite hellish in the diff, but essentially this adds a fixture to properly initiate an AppRunner (with dynamic parameters), and to shut it down during test teardown, to address the issue with AppRunner not being shut down if the test fails.
=> fix: introducing a fixture for proper teardown

src/streamsync/__init__.py, src/streamsync/app_runner.py, src/streamsync/core.py, tests/test_core.py
Making ComponentManager a part of session as a prerequisite to link the state of the UI to each particular session instead of the whole app.
=> chore: linking ComponentManager to session

src/streamsync/app_runner.py, src/streamsync/core.py, src/streamsync/ss_types.py, tests/testapp/ui.json, ui/src/core/index.ts, ui/src/streamsyncTypes.ts
- Include session-specific component tree in EventResponse payload
- Update SessionComponentTree.to_dict to properly merge session-specific and base components, prioritizing session-specific ones
- Add optional `flag` attribute to Component class for CMC control
- Extend frontend Component type with `flag` property
- Implement Component.from_dict class method to enable deserialization
- Introduce frontend core logic to update components based on backend session tree data
=> chore: prepare UI component handling for enhanced session and CMC integration

src/streamsync/core.py
Resolves issue #247 
A minor fix to enable the possibility of having event contexts passed through nested repeater objects where the child repeater object is the item of a parent repeater.
=> Add square barckets to evaluator regex

poetry.lock, pyproject.toml, src/streamsync/core.py, tests/test_core.py
I replaced pandas serialization with the use of the Dataframe Interchange Protocol. It made it possible to cover `polars` at the same time. I have added unit test for polars to ensure it serialize.
* feat: implement the usage of dataframe interchange protocol for serialization
implement #222
---
The hello application using dataframe part is still running.
=> feat: add serialiser for Polars using Dataframe Interchange Protocol

src/streamsync/ui_manager.py
Adds a `_prepare_value` for `StreamsyncUIManager` class, to utilize inside `_create_component`. For `dict`, it uses `json.dumps`, and casts to `str` for the rest of the types. Allows to use Python types when defining content for CMCs, for example:
```py
ui.SliderInput({"minValue": 0, "maxValue": 300, "stepSize": 1}) # uses int literals
```
By default, this triggers `TypeError: template.replace is not a function` on the frontend; this fix allows to avoid it.
=> fix: convert all content values to strings

src/streamsync/core.py, src/streamsync/core_ui.py, src/streamsync/ui.py, src/streamsync/ui_manager.py, tests/test_ui.py, ui/tools/generator.js
Pycharm does not currently support autocompletion on TypedDict passed as an argument to a method. This problem does not seem to be really addressed in their roadmap.
https://youtrack.jetbrains.com/issue/PY-54151/TypedDict-completion-at-callee-does-not-work-for-methods
On the other hand, Pycharm supports autocompletion on static methods of a class.
I propose a draft to manage the component tree as a context variable. This pattern offer 2 advantages :
* all the methods of ui manager can be static
* a developper than build an extension can manipulate the component tree easily inside its extension
---
https://github.com/FabienArcellier/streamsync/issues/40
---
---
I test this implementation on event handler and async event handler
=> fix: added support for autocompletion on the low ui approach for pycharm

src/streamsync/core_ui.py
CMC components are not removed during ingestion. Fixes a bug where CMCs get "cleared" after builder component update.
=> fix: avoid removal of CMCs during ingestion

src/streamsync/core_ui.py, src/streamsync/ui_manager.py
Fix for improper mechanism of determining position (using component id instead of parent id). Fixes a bug of components being "prepended" instead of "appended" to the parent.
=> fix: logic for determining position

src/streamsync/core_ui.py, src/streamsync/ui_manager.py, ui/src/builder/BuilderSettings.vue, ui/src/builder/BuilderSidebarTree.vue, ui/src/builder/BuilderTreeBranch.vue, ui/src/builder/useComponentActions.ts, ui/src/builder/useDragDropComponent.ts, ui/src/core/auditAndFix.ts, ui/src/core/index.ts, ui/src/core_components/content/CoreLink.vue, ui/src/core_components/other/CoreRepeater.vue, ui/src/core_components/root/CoreRoot.vue, ui/src/renderer/ComponentProxy.vue, ui/src/renderer/ComponentRenderer.vue, ui/src/streamsyncTypes.ts
I refactored `flag` to `isCodeManaged` to improve readability.
Also,
**Frontend:**
Some position-related fixes:
- Insertion position in `useComponentActions` is independent of CMCs
- Higher siblings in `useComponentActions` don't have their positions incremented. Before, when inserting a BMC before a CMC, that'd increment the position of the CMC.
- AuditAndFix will ignore CMCs when fixing positioning.
- I added a more descriptive `getComponentChildren` to get children, with filters for BMC and CMC, also orders BMC first and CMC later. I intend to replace all references of `getComponents(parentId)` after release.
**Backend:**
- I made a change in the backend's `determine_position` to ignore BMCs. We now have, for example, two components with position 0, but BMCs are always rendered first. …
=> refactor: Change flag to isCodeManaged

src/streamsync/core_ui.py, src/streamsync/ui_manager.py
Adding a mechanic to keep the count of pages in component trees, and to add predefined keys & IDs for pages if case if they're not provided by user. Fixes a bug with losing CMC page focus upon app code update.
=> chore: preset IDs for pages

ui/src/core_components/other/CoreRepeater.vue
The repeater is invisible when the application is running and the last element has been deleted. The default slot remains visible in edit mode.
fix #223 (maybe)
=> feat: repeater triggers exception when the last item is removed from linked state element

.github/workflows/publish.yml, alfred/publish.py
The command `alfred publish` will trigger a new release of pypi package.
* check it's on master
* check there is no waiting change in master
* check the version number in the manifest has changed
* ask confirmation about the version number related to the previous one
* create a tag and push the tag to the repo
The deployment is trigger on github action
* run the CI a last time to check everything is ok (for exemple, check ui binding generation)
* publish the package on pypi
=> chore:configure pypi package deployment when tagging a new release

ui/src/renderer/RenderError.vue
This was causing this warning:
```
[@vue/compiler-sfc] `defineProps` is a compiler macro and no longer needs to be imported.
```
=> chore: removed unnecessary import

src/streamsync/__init__.py
fix #369 
You have to write ``ss.core.State`` instead of ``ss.State``
```python
import streamsync as ss
class MyappSchema(ss.core.State):
title: str
class AppSchema(ss.StreamsyncState):
my_app: MyappSchema
counter: int
initial_state = ss.init_state({
"counter": 0,
"my_app": {
"title": "Nested value"
}
}, schema=AppSchema)
```
=> fix: import for State, for using State Schema, is missing in streamsync highlevel import

docs/docs/backend-driven-ui.md, docs/docs/event-handlers.md, src/streamsync/core.py, src/streamsync/core_ui.py, src/streamsync/ui_manager.py, tests/backend/fixtures/core_ui_fixtures.py, tests/backend/test_core.py, tests/backend/test_ui.py
On a click or an event, a developer can consult the identifier at the origin of the event from the context. This allows it to adapt the behavior of its event handler or to retrieve the parent to add interface components.
```python
def increment(state, context):
print(context['target'])
```
```python
def increment(state, ui, context):
container = ui.parent(context['target'])
with ui.find(container):
pass
```
```python
def increment(state, ui, context):
container = ui.parent(context['target'], level=3) # third parent
with ui.find(container):
pass
```
* add a documentation section about `Context` into [EventHandler](https://www.streamsync.cloud/event-handlers.html)
=> feat: capture the component that trigger an event in context

src/streamsync/core_ui.py
Allows to exclusively retrieve owned components of a dependent tree. This helps to avoid "assuming control" over base components during preinitialized components (base CMC tree) ingestion in session tree.
=> fix: adding "owned_only" flag for to_dict method of DependentComponentTree

src/streamsync/__init__.py, src/streamsync/app_runner.py, src/streamsync/core.py, src/streamsync/core_ui.py, src/streamsync/ui_manager.py, src/ui/src/streamsyncTypes.ts, tests/backend/fixtures/core_ui_fixtures.py, tests/backend/test_ui.py
This is a refactoring proposal to make the notion of component tree simpler. This refactoring removes the 3 distinct classes that inherit from each other to represent the 3 trees. It removes cascading inheritance and method overloading.
There is a single class `ComponentTree` class that can combine fragments. One fragment for BMC, one for CMC, one for SMC. A fragment can be frozen to lock its contents. Fragments are an instance of the same `ComponentTreeFragment` class.
The application contains 2 tree construction methods. `build_base_component_tree` which builds the tree the application needs upon loading with a fragment for BMCs and CMCs. `build_session_component_tree` builds a tree dedicated to the user session with 3 fragments, one fragment for SMCs, one for CMCs and a frozen fragment …
=> refact: proposal for a new design arround component tree

.github/workflows/docs.yml
This PR creates a workflow that triggers the `mintlify-action` workflow in anant-writer/docs
The reason this isn't part of the `ci.yml` workflow is because `ci.yml` runs on pushes to `master` _and_ `dev`, but this should only run on `master`. We could probably still place it in `ci.yml` and add an `if` statement to skip the step if on `dev`, but I figured this was simpler. Lmk if you'd prefer the alternative
Remaining work:
=> docs: add workflow to trigger mintlify in base repo

src/writer/ai.py
Added a descriptive error in case SDK client failed to initialize due to API key not being provided.
=> chore: verbose error for missing API key

src/ui/src/core_components/base/BaseSelect.vue
A quick fix to handle number values in `BaseSelect` (used in `MultiSelect` & `SelectInput`).
[Screencast from 2024-06-28 09-27-30.webm](https://github.com/writer/writer-framework/assets/11815139/69ac333a-f248-44ad-9ff0-2257c5b2f291)
I also did a small refactoring on props definition, because using object is more robust (it does a runtime check)
=> fix: `BaseSelect` handle `number` value. WF-28

tests/backend/test_ai.py
Offers a range of tests to verify that Framework methods and classes interact properly with SDK graphs and file functionalities.
=> tests: mock & integration tests for KG/Files SDK functionality

src/ui/src/core_components/base/BaseEmptiness.vue, src/ui/src/core_components/content/CoreMessage.vue, src/ui/src/core_components/content/CoreText.vue, src/ui/src/renderer/ChildlessPlaceholder.vue
Simply hide the `CoreText` using `v-if` in preview mode if the value is `emptyText`. We still display the component in edit mode.
[Screencast from 2024-06-29 14-37-01.webm](https://github.com/writer/writer-framework/assets/11815139/12b438b5-dc39-452c-885e-e996b9e8ddfb)
=> fix: Hide `CoreText` in preview if empty value. WF-20

docs/components/component_page.mdx.tpl, docs/framework/authentication.mdx, docs/framework/backend-driven-ui.mdx, docs/framework/custom-components.mdx, docs/framework/deploy-with-docker.mdx, docs/framework/event-handlers.mdx, docs/framework/frontend-scripts.mdx, docs/framework/quickstart-tutorial.mdx, docs/framework/state-schema.mdx, docs/framework/testing.mdx
There are still dependencies on streamsync in the documentation. I fixed the one I found.
fix #473
=> docs: improve documentation to use writer instead of streamsync

alfred/ci.py, docs/framework/dataframe.mdx, docs/mint.json, src/writer/__init__.py, src/writer/core.py, src/writer/ss_types.py, tests/backend/test_core.py
implement https://github.com/FabienArcellier/writer-framework/issues/65
=> feat: implement editable dataframe to manage dataframe editor component

src/ui/src/core_components/content/CoreDataframe.vue
The issue was too many parameters was given to `String.fromCharCode()` and make and error like "Maximum call stack size exceeded".
In fact, there is no need to try to convert the CSV to base64. So I simply used `Blob` and then `URL.createObjectURL` instead which should be more efficient.
Note, it also improve the mime/type declared, which make the OS open the file with a better software (Libreoffice instead of Text Editor for me)
=> fix(ui): fix `CoreDataFrame` download for big file. WF-39

src/ui/src/builder/BuilderFieldsKeyValue.vue, src/ui/src/builder/BuilderSettingsProperties.vue, src/ui/src/builder/BuilderTemplateInput.vue, src/ui/src/renderer/ComponentProxy.vue, src/ui/src/renderer/instancePath.ts
The issue was `BuilderFieldsKeyValue` didn't interpret the template syntax and try to `JSON.parse` it when navigating between "Static List" and "JSON".
I fixed it relying on `useEvaluator().getEvaluatedFields` which take care of getting the current data and parsing template. It simplify a lot the logic of the component!
It just required that I get and parse `instancePath` in the parent.
Now everything works as expected, if user modify a template value in "Static list" mode, the template is overwiten by the plain JSON value. We still handle the "undo/redo" as expected.
[Screencast from 2024-07-01 23-45-17.webm](https://github.com/writer/writer-framework/assets/11815139/4d831d32-1c40-44f3-82b6-b34c06ed14d8)
=> fix: handle template in `BuilderFieldsKeyValue`. WF-31

src/ui/src/core_components/content/CoreDataframe.vue, src/ui/src/wds/WdsTextInput.vue
Simply add `leftIcon` props to `WdsTextInput` and add a search icon to the dataframe component.
https://github.com/user-attachments/assets/1145b0f6-4d0c-4319-acea-ae932fc6a38f
=> feat(ui): add icon to `WdsTextInput`. WF-36

src/ui/src/core_components/layout/CoreSection.vue, src/ui/src/core_components/layout/CoreSteps.vue, src/ui/src/core_components/layout/CoreTabs.vue
`CoreSelect` displays a dropdown which is cropped by `overflow: hidden`. Removing this CSS rule prevent that
closes #380
https://github.com/user-attachments/assets/395cc4f2-bd39-4eb5-a234-24f3570a511b
=> fix(ui): remove some overflow constraints

src/writer/auth.py, tests/backend/test_auth.py
=> fix: Redirect after authentication on http://localhost without /

package.json, src/ui/vite.config.custom.ts
fix #518
I set the port to match the one specified in the documentation.
---
=> fix: npm run custom.dev run dev server instead of custom.dev

src/ui/src/builder/BuilderSidebarTitleSearch.vue, src/ui/src/builder/BuilderSidebarToolbar.vue, src/ui/src/builder/BuilderSidebarTree.vue, tests/e2e/tests/sidebar.spec.ts
I introduced a component named `BuilderSidebarTitleSearch` which extract the existing search logic of `BuilderSidebarTree` and use it for `BuilderSidebarToolbar`.
I also took the opportunity to improve the accessibility since we use `<i>` elements as button, but they're not focusable and clickable with the keyboard.
And finally, I introduced an E2E test which cover the new feature.
https://github.com/user-attachments/assets/21771c20-02db-4a43-a27a-be11632fb209
=> feat(ui): add filter to `BuilderSidebarToolbar`. WF-42

docs/framework/application-state.mdx, docs/framework/event-handlers.mdx, docs/framework/state-schema.mdx, src/writer/__init__.py, src/writer/app_runner.py, src/writer/core.py, tests/backend/fixtures/writer_fixtures.py, tests/backend/test_core.py
implement https://github.com/FabienArcellier/writer-framework/issues/37
```python
def _increment_counter(state):
state['my_counter'] += 1
_state = wf.init_state({"a": 1, "my_counter": 0})
_state.subscribe_mutation('a', _increment_counter)
_state['a'] = 2 # trigger _increment_counter mutation
```
```python
class MyState(wf.WriterState):
counter: int
total: int
def cumulative_sum(state: MyState):
state.total += state.counter
initial_state = ss.init_state({
"counter": 0,
"total": 0
}, schema=MyState)
initial_state.subscribe_mutation('counter', cumulative_sum)
initial_state['counter'] = 2 # trigger the function cumulative_sum
```
```python
class MyState(wf.WriterState):
counter: int
@wf.property('counter')
def counter_str(self) -> str:
return str(self.counter)
state = …
```
=> feat: trigger a calculated property on mutation

apps/default/ui.json, apps/hello/ui.json, src/ui/src/builder/BuilderSettingsVisibility.vue, src/ui/src/builder/useComponentActions.ts, src/ui/src/renderer/useEvaluator.ts, src/ui/src/writerTypes.ts, src/writer/app_runner.py, src/writer/audit_and_fix.py, src/writer/core_ui.py, tests/backend/fixtures/__init__.py, tests/backend/fixtures/obsoletes/ui_obsolete_visible.json, tests/backend/test_audit_and_fix.py, tests/backend/testapp/ui.json
implement #354 
This PR implement the reverse option that allow a developer to reverse the visibility logic. It also implements binding persistence when the user returns to `Yes`
=> feat: checkbox for inversion of visibility value

apps/hello/main.py, src/ui/src/builder/BuilderHeader.vue, src/ui/src/core/index.ts, src/writer/app_runner.py, src/writer/core.py, src/writer/serve.py, src/writer/ss_types.py, tests/backend/test_serve.py, tests/backend/testapp/main.py
This PR introduces a new feature, **feature flags**.
These are defined in `writer.Config.feature_flags` and carried to the frontend, shipped as part of the `init` package.
The main objective is to allow the development and beta testing of big features (like Workflows) without disrupting the release cycle.
This is a minimal implementation, if necessary, future development can include:
- Setting feature flags via CLI (CLI -> `AppRunner` -> `AppProcess` -> `writer.Config`)
- Filtering available components via feature flag
=> feat: Feature flags

src/ui/src/core/index.ts, src/ui/src/core/templateMap.ts, src/ui/src/writerTypes.ts, src/writer/abstract.py, src/writer/serve.py, src/writer/ss_types.py, tests/backend/test_serve.py
As discussed, Abstract Templates allow users to specify a combination of `baseType` and `writer` (`WriterComponentDefintion`), to create a new component type that merges an existing Vue template with a new, backend-defined component definition.
The goal is to use this for Workflows, where "workflow node" will be a generic template and, for example, "Set state" will be defined from the backend, using "workflow node" as the base type.
=> feat: Abstract components

src/writer/app_runner.py, src/writer/auth.py, src/writer/core.py
This resets the mails when the session is retrieved again in the initialization process. `/static` assets can be retrieved without authentication.
fix #535
=> fix: custom stylesheet and js are not loaded after OIDC authentication

docs/framework/custom-components.mdx
MDX error needed to be fixed to restore Mintlify deployment
=> Fixing custom components error for dev docs

alfred/npm.py, docs/framework/custom-components.mdx, package.json, src/ui/package.json, src/ui/src/core/loadExtensions.ts, src/ui/tools/core.mjs, src/ui/tools/custom_check.mjs
=> fix: custom component name should be constrained explicitely - WF-52

src/ui/src/builder/BuilderTemplateInput.vue
I changed the autocompletion item from `<div>` to `<button>` to improve accessibility and make it focusable. Then, I just had to change a bit the closing autocompletion logic to let time to the browser to focus on the element.
https://github.com/user-attachments/assets/eae9f85f-b0eb-48ae-913c-cfae2803daea
=> feat(ui): handle keyboard navigation on autocomplete. WF-44

docs/codegen/generator_components_pages.mjs, src/ui/tools/generator_storybook.mjs
* chore: run component generator only for core component
* chore: ignore workflowsnode into storybook
=> chore: docs generators run only for core components - WF-62

src/ui/src/components/core/base/BaseInputRange.vue
implement #561, improve #505
The current component did not handle steps composed of decimals like 0.1 and 0.01. This PR adds support to permanently fix issue #225.
Decimal numbers can be quite large. The current implementation is of fixed size. The CSS code is modified so that the size of the popover is dynamic.
=> fix: support for floating numbers and large numbers on the slider

docs/framework/chat-assistant.mdx, docs/framework/product-description-generator.mdx, docs/framework/quickstart-tutorial.mdx, docs/framework/quickstart.mdx, docs/framework/release-notes-generator.mdx, docs/framework/social-post-generator.mdx, src/writer/command_line.py, src/writer/serve.py
=> feat: allow CLI to find a different port - WF-76

src/ui/src/components/core/root/CoreRoot.vue, src/ui/src/core/navigation.ts, src/ui/src/renderer/ComponentRenderer.vue, src/writer/core.py
implement #413 
* modify documentation on section https://dev.writer.com/framework/page-routes#retrieving-the-values
=> feat: pick up the URL variables at the start of the app - WF-55

src/ui/src/builder/BuilderTemplateInput.vue, src/ui/src/renderer/useEvaluator.ts, src/writer/core.py, tests/backend/test_core.py
* feat: handle escape variable in exchange protocol
* feat: handle escape variable in auto-completion
* feat: state support dot variable
=> feat: the WF engine should resolves escaped variables - WF-53

src/ui/src/components/core/base/BaseInputRange.vue
When importing a slider, the initial value is `''`, which throws an error like `TypeError: "".toFixed is not a function`.
Also, we don't handle the step change correctly, which can leads to `RangeError: precision -1 out of range`
https://github.com/user-attachments/assets/abbe608b-d133-4edc-8c82-67376308f3c4
=> fix(ui): fix number format for the input slider

src/ui/src/components/core/layout/CoreTab.vue
The issue was that the tab is randomly visible when receiving Visibility setting from the state object property.
The root cause is `ComponentProxy` try to apply `display: none`, but it collide with `CoreTab`'s `v-show`. The fix is simply to check the visibily in `CoreTab` to adapt `v-show` accordingly.
=> fix(ui): handle visibility from object prop for `CoreTab`. WF-73

docs/framework/ai-module.mdx
Documentation for Knowledge Graph / Function tools usage
=> docs: update ai-module.mdx

src/ui/src/components/core/input/CoreSwitchInput.vue
We used a `ref` to store the state of the input and try to synchronize with `useFormValueBroker`. But in fact, there is no reason to do it since this method already use an optimistic update.
https://github.com/writer/writer-framework/blob/9f4af7b7f5c5bc247bc8174a900d6c98456ef529/src/ui/src/renderer/useFormValueBroker.ts#L47-L52
https://github.com/user-attachments/assets/9c19a653-708d-463d-a82c-4ac7d220925c
=> fix(ui): make `CoreSwitchInput` reactive to state change - WF-81

src/ui/src/components/core/base/BaseControlBar.vue, src/ui/src/components/core/content/CoreJsonViewer.vue
I reused the `BaseControlBar` from annotated text component
=> feat(ui): add copy to clipboard for JSON viewer - WF-25

src/ui/src/components/core/content/CoreText.vue
Very minor fix, cursor (which changes depending on whether the text is clickable) needs fixing because the event is no longer called `click` it’s called `wf-click`.
=> fix(ui): adapt cursor of `CoreText` if attached click event - WF-59

src/writer/ai.py
Changes:
- All messages are being stored in the Conversation in order to properly execute a call to LLM
- Fixed tool call gathering for streaming
- Fixed 400 Bad Request being triggered due to "empty" content
- max_depth set to 5
- Logging fix
- Lint & typing fixes
=> fix: message history for FC

src/ui/src/components/core/content/CoreAnnotatedText.vue, src/ui/src/components/core/content/CoreJsonViewer.vue, src/ui/src/components/shared/README.md, src/ui/src/components/shared/SharedCollapsible.vue, src/ui/src/components/shared/SharedControlBar.vue, src/ui/src/components/shared/SharedJsonViewer/SharedJsonViewer.utils.ts, src/ui/src/components/shared/SharedJsonViewer/SharedJsonViewer.vue, src/ui/src/components/shared/SharedJsonViewer/SharedJsonViewerChildrenCounter.vue, src/ui/src/components/shared/SharedJsonViewer/SharedJsonViewerCollapsible.vue, src/ui/src/components/shared/SharedJsonViewer/SharedJsonViewerObject.vue, src/ui/src/components/shared/SharedJsonViewer/SharedJsonViewerValue.vue
The `BaseJsonViewer` needs to be reused in workflow module, which make it harder to reuse since we have a clear separation of components used in Editor and those used in Renderer.
So we have to introduce a new kind of `shared` components that can be reused in both.
=> chore(ui): move `JsonViewer` in shared components - WF-98

src/ui/src/builder/BuilderApp.vue, src/ui/src/builder/BuilderFieldsTools.vue
I noticed that the builder load **many** components on the loading, which hurts a lot performances.
Many of them could be delayed to be loaded only when visible (like on `v-if="true"`) using `defineAsyncComponent`).
---
Here you can see in action, that `BuilderCodePanel` is loaded only when I open the code editor.
https://github.com/user-attachments/assets/c37741bc-3859-4025-9e0c-1fe66944e17d
And the difference on the bundle
=> chore(ui): split the bundle for `BuilderApp` - WF-96

src/ui/src/components/shared/SharedJsonViewer/SharedJsonViewer.vue, src/ui/src/components/shared/SharedJsonViewer/SharedJsonViewerChildrenCounter.vue, src/ui/src/components/shared/SharedJsonViewer/SharedJsonViewerCollapsible.vue, src/ui/src/components/shared/SharedJsonViewer/SharedJsonViewerObject.vue, src/ui/src/components/shared/SharedJsonViewer/SharedJsonViewerValue.vue
The `SharedJsonViewer` is able to render primitives values, but the type definition is not correct and produce warning in development mode.
=> fix(ui): fix type validation for `SharedJsonViewer` - WF-103

src/ui/src/components/core/content/CoreJsonViewer.vue, src/ui/src/components/shared/SharedJsonViewer/SharedJsonViewer.vue
Add an option to not show the type of the root node when it's an Object or an Array.
https://github.com/user-attachments/assets/830ce2e2-abad-42f5-bed2-a3b29e8f898b
=> feat(ui): add an option `hideRoot` for `CoreJsonViewer` - WF-104

src/writer/ai.py
An error in logic required `finish_reason: "tool_calls"` message to always have `tool_calls: [...]` object – which is possible in certain contexts, but not always true. This fix modifies the logic to detect the `finish_reason` independently.
=> fix: change logic for finish reason processing

src/writer/app_runner.py, src/writer/wf_project.py
Since the IDE information is stored in the .wf folder instead of ui.json, typing quickly in the WF IDE may experience latency.
---
The saving of editing files is carried out asynchronously in a dedicated process. It is no longer blocking. The time spent in the process is reduced to practically zero when making modifications in edit mode.
before (extract using py-spy), the operation of write_files use most of the CPU time.
after, the operation of write_files is not visible anymore. the CPU time consume by websocket stream is very low
=> feat: improve performance in writing wf project - WF-97

src/ui/src/builder/BuilderApp.vue, src/ui/src/builder/BuilderAsyncLoader.vue, src/ui/src/builder/BuilderCodePanel.vue, src/ui/src/builder/BuilderSettings.vue
I recently introduced Async Components, but some of them are massive, and the loading time is noticeable. It renders as blank area, which is not good.
So I used `loadingComponent` property to fill the space during the loading, and improved a bit the loading strategy to improve the UX.
https://github.com/user-attachments/assets/1b817790-03d9-4982-8a95-bf1f1ef70ff2
=> fix(ui): display loader during async loading component

src/writer/app_runner.py, src/writer/wf_project.py
The process can be stuck or stop with an exception. I migrate it to use `multiprocessing.Event` to trigger stop from inside and avoid killing from outside without control.
=> fix: the process of saving project information stops properly in any condition - WF-114

src/writer/ai.py
Enable serialization for messages that contain `tool_calls` but have non-empty `content` – in cases when model generates both `content` and `tool_calls` without separation.
=> chore: serialize tool calls messages with non-empty content

pytest.ini
The warnings issued by pytest were present because `set_token` mark, used in `test_ai.py` to mock Writer API token, was not registered properly. This fix addresses that.
=> fix: register `set_token` mark to avoid pytest warnings

package-lock.json, src/ui/package.json, src/ui/src/builder/BuilderFieldsAlign.vue, src/ui/src/builder/BuilderFieldsPadding.vue, src/ui/src/builder/BuilderFieldsWidth.vue, src/ui/src/builder/BuilderSelect.vue, src/ui/src/builder/BuilderSettingsHandlers.vue, src/ui/src/composables/useFocusWithin.ts, src/ui/src/wds/WdsDropdownMenu.vue
Right now, an event handler has to be selected using a standard select. This works well for small apps, but it’s a bad experience for bigger apps.
https://github.com/user-attachments/assets/cb7d872e-c547-4cd7-9448-b26de96f4b1e
So I reused the `BuilderSelect` and improved a bit to support search. I also integrated the Writer's design for the dropdown ([Figma](https://www.figma.com/design/jgLDtwVwg3hReC1t4Vw20D/.WDS-Writer-Design-System?node-id=128-396&node-type=frame&t=EtUKduJ2Y1FFpYpX-0))
https://github.com/user-attachments/assets/baa6388b-cf1f-4517-9755-f7481d271185
1. implement `WdsDropdownMenu` component that use the design from the design system
2. rework a lot the `BuilderSelect` component
- used the library [floating-ui](https://floating-ui.com/) which is a more robust solution to …
=> feat(ui): use `BuilderSelect` for handlers + implement Design System - WF-45

.github/workflows/ci-e2e.yml, .github/workflows/ci-macos.yml
github actions runners sometimes failed due to lack of memory. Activation of superior runner for end 2 ends tests and for tests on macos.
=> chore: increase github action runner size

.github/workflows/ci-ui-test.yml, package-lock.json, src/ui/package.json, src/ui/src/core/navigation.spec.ts, src/ui/src/core/navigation.ts
It's possible to use `URLSearchParams` instead of complex Regex. As it's a very testable part of the code, it was a good opportunity to introduce Vitest and cover it.
This improvement made me realise that a bug was present, and we didn't serialize the params when converting back the object to hash (`.key = length` was not called).
=> chore(ui): improve hash parsing + setup unit test - WF-72

tests/backend/blocks/test_writernocodeapp.py
Replacing the original functions led to fails on consecutive tests. This avoids it, patching the function in the context of the test.
=> fix: patch with fake_generate_content instead of replacing the original

src/writer/ai.py
An error in logic required `arguments` to always be a proper JSON, which is not the case for function calls with no defined parameters. This fix addresses it by additionally checking whether the parameters were defined for the function, and using this information to avoid "requiring" arguments when preparing the call. Additionally, `parameters` on `create_function_tool` method were made an optional parameter, to allow for clearer syntax when defining functions with zero parameters.
For an extreme edge case, fallback `res` was added to `_gather_tool_calls_messages` to accommodate for scenario when the function was never called for some reason, avoiding a crash.
=> fix: properly process tool calls with zero arguments

src/ui/src/components/workflows/WorkflowsWorkflow.vue, src/ui/src/core/index.ts, src/writer/core.py, src/writer/serve.py, src/writer/ss_types.py, tests/backend/test_app_runner.py, tests/backend/testapp/main.py
This PR is preparation for async jobs. This feature will allow an API endpoint such as `POST /api/job/my_workflow` and later get the result via `GET /api/job/3`.
To facilitate triggering events at this level, this PR introduces "global events" which are `WriterEvent` that don't target a specific component. Therefore, turning `instancePath` into an optional field. Instead, a new `handler` field can be specified to run arbitrary event handlers.
There's of course potential for abuse, so that's why only global events marked as "safe" can be executed. Safe events are produced in "edit" mode. In an upcoming PR, the creation of async jobs will also trigger safe events to run workflows.
=> feat: Global events

src/ui/src/builder/settings/BuilderFieldsAlign.vue
Fix a small regression from https://github.com/writer/writer-framework/pull/638 , the `BuilderFieldsAlign` is not correctly binded to the `v-model` directive.
https://github.com/user-attachments/assets/7d823cfd-47d7-4c7e-860f-43b99db1f3f0
=> fix(ui): fix `BuilderFieldsAlign` binding

src/ui/src/components/core/base/BaseCollapseButton.vue, src/ui/src/components/core/layout/CoreColumn.vue, src/ui/src/components/core/layout/CoreSection.vue, src/ui/src/components/core/layout/CoreSidebar.vue
- The `CoreColumn` displayed the collapse arrow in the wrong direction
- The `CoreSection` title wasn't vertical aligned with the button
- Remove dead CSS code
=> fix(ui): improve design of collapse button

src/ui/src/components/core/input/CoreSliderInput.vue, src/ui/src/components/core/input/CoreSliderRangeInput.vue, src/ui/src/renderer/useFormValueBroker.ts
The default value for `useFormValueBroker` is an empty string. This make some incompatibilities with components that expect a different type of value and produces props warning.
So I added a params `defaultValue` to `useFormValueBroker` to specifiy the default value when it's needed.
=> fix(ui): add default value for Slider

docs/framework/ai-module.mdx
Provides documentation for `writer.ai.ask` / `writer.ai.stream_ask` / `writer.ai.Graph.ask` / `writer.ai.Graph.stream_ask`, with detailed explanation and examples for use cases. Additionally includes some doc fixes.
=> chore(docs): document the usage of `ask` and `stream_ask` methods

docs/framework/builder-basics.mdx, docs/framework/introduction.mdx
This PR removes the `#` from image URLs in the Introduction and Builder Basics docs.
=> docs: Fix image URLs in Intro and Builder Basics

src/ui/src/builder/BuilderModal.vue, src/ui/src/builder/BuilderSelect.vue, src/ui/src/builder/settings/BuilderFieldsAlign.vue, src/ui/src/builder/settings/BuilderFieldsColor.vue, src/ui/src/builder/settings/BuilderFieldsKeyValue.vue, src/ui/src/builder/settings/BuilderFieldsObject.vue, src/ui/src/builder/settings/BuilderFieldsPadding.vue, src/ui/src/builder/settings/BuilderFieldsShadow.vue, src/ui/src/builder/settings/BuilderFieldsText.vue, src/ui/src/builder/settings/BuilderFieldsWidth.vue, src/ui/src/builder/settings/BuilderSectionTitle.vue, src/ui/src/builder/settings/BuilderSettingsBinding.vue, src/ui/src/builder/settings/BuilderSettingsHandlers.vue, src/ui/src/builder/settings/BuilderSettingsProperties.vue, src/ui/src/builder/settings/BuilderSettingsVisibility.vue, src/ui/src/builder/settings/BuilderTemplateInput.vue, src/ui/src/builder/settings/constants/builderFieldsCssTabs.ts, src/ui/src/builder/sharedStyles.css, src/ui/src/wds/WdsFieldWrapper.vue, src/ui/src/wds/WdsTab.vue, src/ui/src/wds/WdsTabs.vue, src/ui/src/wds/WdsTextInput.vue, src/ui/src/wds/WdsTextareaInput.vue, tests/e2e/tests/state.spec.ts, tests/e2e/tests/stateAutocompletion.spec.ts
- Use `WdsTextField` and `WdsFieldWrapper` in the builder to respect the design system.
- Adapt the design on settings fields to make it compliant
|---|---|
| ![image](https://github.com/user-attachments/assets/21b99b1a-dcf2-4d03-86ae-65b379dba410) | ![image](https://github.com/user-attachments/assets/27707711-9263-4a3f-b968-52ca5d881dab) |
| ![image](https://github.com/user-attachments/assets/26abd2b2-c891-41ad-9134-723f5cc61949)  | ![image](https://github.com/user-attachments/assets/b53ffd53-7b37-455d-a41d-53947a4c7031) |
| ![image](https://github.com/user-attachments/assets/75c6afe0-4639-41ae-8cfa-42fd941cdd04) | ![image](https://github.com/user-attachments/assets/99c5aead-9d87-4b5b-acf7-9a81e2515de9) |
=> feat(ui): use design system in builder - WF-127

src/ui/src/builder/settings/BuilderSettingsProperties.vue, src/ui/src/wds/WdsFieldWrapper.vue
Restore the field unit removed in https://github.com/writer/writer-framework/pull/657
|---|---|
| ![image](https://github.com/user-attachments/assets/a0a5dfde-8b6b-4e74-a234-72ddbfcb73a6) | ![image](https://github.com/user-attachments/assets/3ba0728b-b013-42b0-8e8e-7309776f379b) |
=> fix(ui): re-introduce fields unit in Builder - WF-127

src/ui/src/components/core/other/CoreTimer.vue
The `CoreTimer` component has no minimum width, which makes it indivisibles inside a `CoreHortizontalStack` component because these components force child components to have `width: auto` (see #600).
I double-checked, and it seems `CoreTimer` the only component affected by this issue.
=> fix(ui): add `min-width` to `CoreTimer` - WF-130

src/ui/src/components/core/content/CoreDataframe.vue, src/ui/src/components/core/content/CoreDataframeLegacy.vue
The `CoreDataframe` component has a custom background color set with `dataframeBackgroundColor` variable. This custom background prevents the user to seeing that this component is being selected in Builder mode.
The workaround is to simply `unset` the background color when the component has a `.selected` class.
https://github.com/user-attachments/assets/c8431363-6013-4df0-a1ac-3fc72978a8cd
=> fix(ui): adapt Dataframe bg color when selected - WF-131

src/ui/src/builder/BuilderSelect.vue, src/ui/src/builder/settings/BuilderSettingsHandlers.vue, src/ui/src/builder/settings/BuilderSettingsProperties.vue, src/ui/src/wds/WdsDropdownMenu.vue, src/ui/src/wds/WdsFieldWrapper.vue
Take in account [feedbacks](https://www.figma.com/board/ujJsOLjc2aPSwA7lSclTUC/UI-feedback?node-id=0-1&p=f&t=sSjPKxHnQsj13Aoh-0) after the https://github.com/writer/writer-framework/pull/657
- use `WdsButton` in builder
- avoid rendering empty sections in builder
- set `BuilderSelect` WDS focus state
- set `BuilderSelect`'s dropdown vertical only
- improve `WdsDropdownMenu` search bar
=> feat(ui): Improve wds builder

src/ui/src/builder/BuilderApp.vue, src/ui/src/builder/BuilderHeader.vue, src/ui/src/builder/BuilderSwitcher.vue, src/ui/src/builder/settings/BuilderFieldsColor.vue, src/ui/src/builder/settings/BuilderFieldsKeyValue.vue, src/ui/src/builder/settings/BuilderFieldsShadow.vue, src/ui/src/builder/settings/BuilderFieldsText.vue, src/ui/src/builder/settings/BuilderFieldsWidth.vue, src/ui/src/builder/settings/BuilderSettings.vue, src/ui/src/builder/settings/BuilderSettingsAPICode.vue, src/ui/src/builder/settings/BuilderSettingsActions.vue, src/ui/src/builder/settings/BuilderSettingsBinding.vue, src/ui/src/builder/settings/BuilderSettingsMain.vue, src/ui/src/builder/settings/BuilderSettingsProperties.vue, src/ui/src/builder/settings/BuilderSettingsVisibility.vue, src/ui/src/builder/settings/BuilderTemplateInput.vue, src/ui/src/renderer/ComponentProxy.vue, src/ui/src/renderer/RendererNotifications.vue, src/ui/vite.config.custom.ts
The custom component built using `npm run custom.build` was not working correctly because the `provide/inject` failed.
The error was, we bundled `injectionKeys` in the `template.umd.js` , So it makes defining two different `Symbol` which point to a different `provide`.
It's because the `rollupOptions.external` in Vite config pointed to `../injectionKeys`, but we sometime use the alias `@/injectionKeys`. So I simply use `path.resolve` to be sure `injectionKeys` are not bundled in custom components.
=> fix(ui): avoid bundling `injectionKeys` in custom components

package-lock.json, src/ui/package.json, src/ui/vite.config.ts
We want the user to be able to customize any style using `import_stylesheet` feature. But, actually, he needs to use `!important` everywhere to make his rules have more weight.
The solution is to use CSS cascade layers to redefine the priority of rules easily. We can move all Writer Framework CSS into a layer `wf`. This makes other CSS rules have more priority by default.
So I just installed PostCSS and a plugin `postcss-assign-layer`. This automates surrounding our styles by layers.
```css
/* static/custom.css */
.custom { background: red; }
```
```py
initial_state.import_stylesheet("theme", "/static/custom.css")
```
=> feat(ui): use CSS layer to let user customize app - WF-57

src/ui/src/builder/BuilderSelect.vue, src/ui/src/builder/BuilderTooltip.vue, src/ui/src/wds/WdsDropdownMenu.vue
The `BuilderSelect` trigger has overflow issues with long text containing breakable content. The trick was just a missing `white-space: nowrap` rule.
I also took the opportunity to add a tooltip to the `BuilderSelect`'s trigger.
=> fix(ui): handle long text in `BuilderSelect`

src/ui/src/renderer/ComponentProxy.vue
We want to disable the component "selected" state when the style of the component is changed (like when the user changes the background). But actually, this is done when **any** of `evaluatedFields` changes.
The fix was simply to run the behavior only when a "Style" field change. So I just tweaked a bit the `watch` source in `ComponentProxy`.
https://github.com/user-attachments/assets/d808a0ef-ed89-4d31-8805-1e38153903b0
=> fix(ui): avoid reseting the "selected" state on all field change - WF-155

src/ui/src/builder/sidebar/BuilderSidebarToolkit.vue, src/ui/src/components/core/content/CoreChatbot.vue, src/ui/src/components/shared/SharedImgWithFallback.spec.ts, src/ui/src/components/shared/SharedImgWithFallback.vue, src/ui/src/components/workflows/abstract/WorkflowsNode.vue, src/ui/src/composables/useAssetContentType.spec.ts, src/ui/src/composables/useAssetContentType.ts, src/ui/src/utils/url.spec.ts, src/ui/src/utils/url.ts
Introduce a new component `ShareImgWithFallback` which takes an array of URLs for the image and uses the first successful URL.
This component uses a new hook `useAssetContentType` that takes care of fetching the `Content-Type` header of the asset URL, and handles the concurrency / cache. The `Content-Type` is needed because the server might serve a default `text/html` if the assets doesn't exist.
It also fix an edge case wherein the application run is an URL path like `https://streamsync-dev.osc-fr1.scalingo.io/hello/`, we are trying to import asset from the root (`https://streamsync-dev.osc-fr1.scalingo.io/`) and not the path `/hello`
I also took the opportunity to test the Vue.js component using [Vue Test Utils](https://test-utils.vuejs.org/)
This change is transparent for the user.
=> chore(ui): improve icon fetching. WF-141

src/ui/src/builder/panels/BuilderPanelSwitcher.vue
When dragging a new component in the page, the placeholder marker is displayed on top of the open panel. I just fixed it with a `z-index` to make the `BuilderPanelSwitcher` on top of `ComponentRenderer`.
=> fix(ui): floating insertion marker overflow - WF-158

src/ui/src/components/core/content/CoreProgressBar.vue
I forgot to hide the progression when the `CoreProgressBar`'s progression is `undefined` (which is the case in "indeterminate" state when no `value` is provided).
So it actually displays `NaN%` when the component settings are `value === undefined && displayPercentage === true`. It's better to simply not display the percentage in this situation.
=> fix(ui): hide `CoreProgressBar` progression in indeterminate state

package-lock.json, tests/e2e/package.json
CI pipeline is broken due to update of ubuntu 24.04.
According to the [Ubuntu 24.04 release notes](https://discourse.ubuntu.com/t/noble-numbat-release-notes/39890) in the section [Year 2038 support for the armhf architecture](https://discourse.ubuntu.com/t/noble-numbat-release-notes/39890#year-2038-support-for-the-armhf-architecture-5)
> More than a thousand packages have been updated to handle time using a 64-bit value rather than a 32-bit one, making it possible to handle times up to 292 billion years in the future.
* update playwright to support ubuntu 24.04
=> fix: update playwright to support ubuntu 24.04 agent for e2e test

pyproject.toml
* feat: change include list in pyproject.toml to use path dictionaries with format specified for sdist and wheel
*wheel package has all the files*
=> writer framework build process is compatible with poetry 2.0.0

src/ui/src/builder/BuilderTree.vue, src/ui/src/builder/builderManager.ts, src/ui/src/builder/panels/BuilderLogWorkflowExecution.vue, src/ui/src/builder/sidebar/BuilderSidebarComponentTree.vue, src/ui/src/builder/sidebar/BuilderSidebarComponentTreeBranch.vue, src/ui/src/builder/sidebar/BuilderSidebarPanel.vue, src/ui/src/builder/sidebar/BuilderSidebarToolkit.vue, src/ui/src/builder/sidebar/composables/useComponentsTreeSearch.spec.ts, src/ui/src/builder/sidebar/composables/useComponentsTreeSearch.ts, src/ui/src/components/workflows/base/WorkflowNavigator.vue, src/ui/src/core/index.ts, src/ui/src/renderer/ComponentRenderer.vue, src/ui/src/wds/WdsTextInput.vue
When searching for a component in the tree, we start to display only components matching the query, or those containing children matching the query.
It'll
- collapse component that doesn't match the query (with a small animation)
- display the number of matches
- allow to clear search with a button
Before
https://github.com/user-attachments/assets/0f0ca13e-711d-4861-9cbc-058acdd00012
After
https://github.com/user-attachments/assets/a31a137a-61e6-4811-a513-e536e88e9c40
=> feat(ui): improve component tree search. WF-183

src/ui/src/builder/BuilderTooltip.vue
|---|---|
| ![Screenshot 2025-02-20 at 17 49 09](https://github.com/user-attachments/assets/1da4cd79-0d5a-4176-be27-df9549b50e3e) | ![Screenshot 2025-02-20 at 17 48 57](https://github.com/user-attachments/assets/89f0e167-8388-4efd-a417-19b604f2a48c) |
=> fix(ui): use word break in tooltip

src/writer/__init__.py
Helps avoiding a `NameError` that prevents a launch due to missing `ui.py`.
=> fix: replace class reference on type hint of `init_ui`

src/writer/blocks/writercompletion.py
Make it consistent with `WriterInitChat`
https://github.com/writer/writer-framework/blob/7de351f298d78ec90a6657c214924f621cd4388b/src/writer/blocks/writerinitchat.py#L5
=> fix(writer): bump default model for workflow completion block - WF-175

src/ui/src/core/index.ts, src/writer/app_runner.py, src/writer/serve.py, tests/backend/test_app_runner.py
This PR switches [asyncio.Condition](https://docs.python.org/3/library/asyncio-sync.html#asyncio.Condition) for [asyncio.Queue](https://docs.python.org/3/library/asyncio-queue.html) when dealing with announcements, providing a more flexible architecture that also allows for announcement payloads to be sent.
This enabled using the announcement payload to send mail, making it possible to send mail when outside the app process. For example, for system notification purposes.
This feature was applied to send `pip install` logs.
=> feat: Announcement queue with mail support

src/ui/src/builder/BuilderGraphSelect.spec.ts, src/ui/src/builder/BuilderGraphSelect.vue, src/ui/src/builder/BuilderSelect.spec.ts, src/ui/src/builder/BuilderSelect.vue, src/ui/src/builder/builderManager.ts, src/ui/src/builder/settings/BuilderFieldsTools.vue, src/ui/src/builder/settings/BuilderFieldsWriterGraphId.vue, src/ui/src/builder/settings/BuilderSettingsHandlers.vue, src/ui/src/builder/settings/BuilderSettingsProperties.vue, src/ui/src/components/core/root/CoreRoot.vue, src/ui/src/composables/useListResources.spec.ts, src/ui/src/composables/useListResources.ts, src/ui/src/composables/useLocalStorageJSON.spec.ts, src/ui/src/composables/useLocalStorageJSON.ts, src/ui/src/core/index.ts, src/ui/src/wds/WdsCheckbox.vue, src/ui/src/wds/WdsDropdownMenu.spec.ts, src/ui/src/wds/WdsDropdownMenu.vue, src/ui/src/wds/WdsSkeletonLoader.vue, src/ui/src/wds/WdsTag.vue, src/ui/src/writerTypes.ts, src/writer/app_runner.py, src/writer/blocks/writeraddtokg.py, src/writer/serve.py, src/writer/ss_types.py
This feature introduces a new selector that allows the user to select a knowledge graph from Writer's platform instead of copy/pasting the UUID.
| in workflow block | in tools editor |
|---|---|
| ![Screenshot 2025-02-11 at 17 53 43](https://github.com/user-attachments/assets/2de10f51-5121-4b6a-b9b6-2e743b456219) | ![Screenshot 2025-02-11 at 17 54 06](https://github.com/user-attachments/assets/8a3bbc7b-3c5b-4555-a226-7c9dec715d55) |
- introduce a new event called `listResources` that gets the list of Writer's graph (and will support other things later)
- make `BuilderSelect` and `WdsDropdownMenu` compatible with multi-selector
- introduce a new field `FieldType.WriterGraphId` to support graph selector for component's settings
=>  feat: setup knwoledge graph selector - WF-138 

src/ui/src/components/core/root/CoreRoot.vue
All exported shared styles were included for `CoreRoot`, but some of them should not.
=> fix(ui): remove extra attributes for `CoreRoot`

src/ui/src/components/core/other/CoreButton.spec.ts, src/ui/src/components/core/other/CoreButton.vue, src/ui/src/components/core/other/CoreHtml.spec.ts, src/ui/src/components/core/other/__snapshots__/CoreHtml.spec.ts.snap, src/ui/src/wds/WdsButton.vue
The `CoreButton` was using the default selected background from the editor which makes text barely visible.
It was also a good opportunity to properly disable the button when the property `isDisabled` is set.
| edit mode | preview mode |
|--|---|
|  ![Screenshot 2025-03-12 at 12 30 38](https://github.com/user-attachments/assets/94a44db3-06cd-4052-8187-c7b35eee5337) | ![Screenshot 2025-03-12 at 12 30 48](https://github.com/user-attachments/assets/e03770a1-f0fc-47c0-b524-de489f0156c9) |
=> fix(ui): adapt `CoreButton` selected & disabled state - WF-191

src/ui/src/components/core/other/__snapshots__/CoreHtml.spec.ts.snap, src/ui/src/components/shared/SharedMoreDropdown.vue, src/ui/src/core/useSourceFiles.spec.ts, src/ui/src/core/useSourceFiles.ts
When user edits a source file with an external editor, we need to reflect this change in `sourceFileDraft` (monaco editor in the panel).
=> fix(ui): refresh ext. source file changes on code editor

src/ui/src/builder/settings/BuilderFieldsAlign.vue, src/ui/src/builder/settings/BuilderFieldsPadding.vue, src/ui/src/builder/settings/BuilderFieldsTools.vue, src/ui/src/builder/settings/BuilderFieldsWidth.vue, src/ui/src/builder/settings/BuilderSettingsHandlers.vue
Fix warning of Vite build saying
```
(!) src/ui/src/builder/BuilderGraphSelect.vue is dynamically imported by AAA but also statically imported by BBB, dynamic import will not move module into another chunk.
```
This will force to bundle `@floating-ui/vue` to be split into a separated chunk and saves 14kb
```diff
-../writer/static/assets/BuilderApp-DVqlivId.js                                         60.40 kB │ gzip:    21.46 kB
-../writer/static/assets/BuilderSettings-oWe5fV87.js                                    79.92 kB │ gzip:    22.79 kB
+../writer/static/assets/BuilderApp-CljhirPm.js                                         45.20 kB │ gzip:    15.55 kB
+../writer/static/assets/BuilderSettings-BHSMljIi.js                                    75.66 kB │ gzip:    21.22 kB …
```
=> chore(ui): use dynamic import for `floating-ui`

src/ui/src/builder/sidebar/BuilderSidebarComponentTreeBranch.vue
The horizontal scroll when user clicks on the component tree is annoying. We only scroll in the tree when the user select a component from the UI.
=> fix(ui): prevent scroll on click inside Tree sidebar - WF-232

src/ui/src/components/workflows/WorkflowsWorkflow.vue
once `isPerfected` is `true`, we don't select the node. So we considerate a small movement as a missclick (the user click but drag few pixels)
I also took the opportunity to replace some `ref` by `shallowRef` to improve the performance.
=> fix(ui): improve node selection in blueprint - WF-226

src/ui/src/components/core/input/CoreCheckboxInput.vue, src/ui/src/components/workflows/WorkflowsWorkflow.vue, src/ui/src/components/workflows/abstract/WorkflowsNode.vue, src/ui/src/renderer/ComponentProxy.vue, src/ui/src/renderer/RenderError.vue
Customize `RenderError.vue` to display a `WorkflowsNode` component for invalid workflow blocks.
It also renders the `outs` of the nodes.
=> fix(ui): handle unknown component in Blueprint - WF-193

src/ui/src/components/blueprints/abstract/BlueprintsNode.vue, src/ui/src/components/core/content/CoreDataframe.vue, src/ui/src/components/core/layout/CoreStep.vue, src/ui/src/components/core/layout/CoreTab.vue, src/ui/src/renderer/sharedStyles.css
Adapt the selected state in UI buider to have an outline instead of a simple background color change.
It makes the UX more clear and consistent with Blueprint mode.
=> feat(ui): align UI select state across UI / Blueprint  - WF-240

src/ui/src/core/index.ts, src/writer/app_runner.py
- When deployed stateEnquiries would take too long and trigger stateEnquiries themselves. Fixed.
- Replaced deprecated Pydantic method
=> fix: Avoid recursive stateEnquiries when latency is high

src/ui/src/builder/builderManager.ts, src/ui/src/builder/useComponentActions.ts, src/ui/src/main.ts
@madeindjs I fixed the undo reliability issues. Basically the `change-multiple-coordinates` transaction remained open when there were no entries. This ended up really disrupting undo/redo, especially because change coordinates is called on every `mouseup`.
I also added some stuff that was useful for debugging this and a warning that'd have caught this. Please take a look.
=> fix: Undo reliability issues

src/ui/src/builder/BuilderHeader.spec.ts, src/ui/src/builder/BuilderHeader.vue, src/ui/src/composables/useApplicationCloud.ts, src/ui/src/writerApi.ts
- compute the agent URL on frontend side
- rely on `status` of the agent to detect if the application is deployed or not
- improve types
- fix runtime warning
=> fix(ui): improve writer agent deployment

src/ui/src/components/blueprints/BlueprintsBlueprint.vue, src/ui/src/utils/geometry.spec.ts, src/ui/src/utils/geometry.ts, src/ui/src/utils/math.ts
Improve experience for positioning blueprint nodes:
1. introduce an internal grid in Blueprint canvas 
2. Introduce key listen to move the selected component
3. Prevents user from overlaying two nodes 
https://github.com/user-attachments/assets/7010ad56-a05a-4e8d-9be3-ad9974c4edf2
=> feat(ui): introduce blueprint snap grid - WF-297

src/writer/autogen.py
Fixes the error when trying to use the Autogen in local environment, without `X-Agent-Token` present.
=> fix: autogen X-Agent-Token header retrieval

src/ui/src/components/blueprints/abstract/BlueprintsNode.vue
Use `convertAbsolutePathtoFullURL` to import `/status/success.svg` from the origin of the app instead of the root of the URL.
=> fix(ui): makes blueprint assets absolute instead of relative

src/ui/src/builder/BuilderApp.vue, src/ui/src/builder/BuilderToasts.vue, src/ui/src/builder/builderManager.ts, src/ui/src/builder/panels/BuilderLogBlueprintExecutionTrace.vue, src/ui/src/builder/settings/BuilderSettingsActions.vue, src/ui/src/builder/useComponentActions.ts, src/ui/src/builder/useComponentClipboard.ts, src/ui/src/components/blueprints/base/BlueprintToolbar.vue, src/ui/src/wds/WdsCheckbox.vue, src/ui/src/writerTypes.ts
Use the browser clipboard instead of Vue.js state when copying a component.
This allow the user to copy a component from an agent, and paste it to another agent.
=> feat(ui): copy component in clipboard to share it - WF-271

src/ui/src/builder/settings/BuilderTemplateInput.vue, tests/e2e/tests/stateAutocompletion.spec.ts
Close the bracket when autocomplete, example when typing `@{po`, autocomplete with `@{post}`.
=> fix(ui): autocomplete with closing `}` - WF-372

src/ui/src/components/core/content/CoreDataframe.vue, src/ui/src/utils/base64.ts
In `CoreDataframe`, we decode the data URL to binary data using `fetch`. This causes an issue in environments where there are strict CORS rules.
So we now decode the data URL ourselves to avoid using `fetch`.
=> fix(ui): prevent CORS issue on Dataframe data loading - WF-383

src/writer/blocks/httprequest.py
Default timeout is 20 seconds – which is too short for some synchronous AI operations. This sets the timeout to 180 seconds.
=> chore: increase timeout for `HTTPRequest` block

src/writer/app_runner.py
It's not possible to rename file in some environment (like S3/Fuse), so we get an error like `[Errno 38] Function not implemented`.
The workaround is to try `os.rename`, and then fallback to "copy/delete" operation if an error happens.
=> fix(writer): handle file operation on S3 - WF-386

src/ui/src/wds/WdsButton.vue, src/ui/src/wds/WdsButtonLink.vue, src/ui/src/wds/WdsDropdownMenu.vue, src/ui/src/wds/WdsTag.vue
Without `type="button"`, the button is considerate as a Submit button, which sends the parent form and produces a page reloading
=> fix(ui): setup `type="button"` for `WdsButtonLink`

package-lock.json, src/ui/package.json, src/ui/src/builder/BuilderApp.vue, src/ui/src/builder/BuilderHeader.vue, src/ui/src/builder/BuilderSwitcher.vue, src/ui/src/builder/BuilderTree.vue, src/ui/src/builder/settings/BuilderSettingsActions.vue, src/ui/src/builder/sidebar/BuilderSidebar.vue, src/ui/src/builder/sidebar/BuilderSidebarButton.vue, src/ui/src/builder/sidebar/BuilderSidebarComponentTreeBranch.vue, src/ui/src/builder/sidebar/BuilderSidebarPanel.vue, src/ui/src/builder/sidebar/BuilderSidebarToolkit.vue, src/ui/src/components/blueprints/base/BlueprintToolbar.vue, src/ui/src/wds/WdsButtonSplit.vue, tests/e2e/tests/blueprints.spec.ts, tests/e2e/tests/builderFieldValidation.spec.ts, tests/e2e/tests/button.spec.ts, tests/e2e/tests/components.spec.ts, tests/e2e/tests/image.spec.ts, tests/e2e/tests/reuse.spec.ts, tests/e2e/tests/sidebar.spec.ts, tests/e2e/tests/stateAutocompletion.spec.ts, tests/e2e/tests/undoRedo.spec.ts
Implement a new layout with
- the header in black with a centered menu switcher
- a left sidebar containing the panel of Components Tree and Components List
I also updated the library `@fontsource-variable/material-symbols-outlined` to get newer icons
=> feat(ui): introduce new layout - WF-375
