pyproject.toml

Feel free to change the dependency version if you think it is too tight.

1. Fix the missing dependencies for build and test

---

ui/src/core/templateMap.ts
ui/src/core_components/CoreIcon.vue

An icon taken from remixicon can be displayed. It is retrieved from Content / Icon

icon component to display icon from remixicon library

---

src/streamsync/app_runner.py
src/streamsync/core.py

Adding call to logging.basicConfig in app_runner.py; 
Refactoring core.py to reduce code repetition and accomodate for all available logging levels.

Enabling warning & info messages in app logs

---

apps/hello/ui.json
src/streamsync/app_templates/hello/ui.json
src/streamsync/core.py
ui/src/core_components/CorePagination.vue

I enriched the previous PR to set up a sanitization mechanism for changing pages and changing page sizes.

add sanitization on pagination component

---

src/streamsync/serve.py
tests/__init__.py
tests/test_app_runner.py
tests/test_core.py
tests/test_serve.py

Updated tests in `test_core.py`, `test_app_runner.py`, and `test_serve.py` to use dynamic paths derived from `test_app_dir` in `__init__.py` of the `tests` directory. This ensures consistent path resolution across different environments.

Making existing tests location-agnostic; add conditional check for server static path before mounting

---

apps/hello/Dockerfile
docs/docs/deploy-with-docker.md

docs(#245): docker image build python version lock

---

ui/src/builder/BuilderInstanceTracker.vue

Really small but annoying thing
https://github.com/streamsync-cloud/streamsync/assets/649972/2b17fcfb-de2d-48f5-8724-860fceb7f67b

fix: builder shortcuts visibility problem 

---

docs/docs/modifying-app-ui-through-backend.md

Documentation describing the usage of features associated with code-managed components.

docs: code managed components

---

alfred/ci.py
alfred/npm.py
package.json
ui/package.json

check in continuous integration if the ui binding is up to date. If it's not, it raise an error and show the following error message to user :
```
UI binding is incomplete and has to be regenerated with `alfred npm.codegen.binding.ui`
```

chore: check if ui binding is up to date in continuous integration

---

docs/docs/modifying-app-ui-through-backend.md

Adding a note to provide an id for a component if it is intended to be retrieved by find method later.

docs: update modifying-app-ui-through-backend.md

---

ui/src/core_components/other/CorePagination.vue

fix: Empty pagination list count

---

docs/codegen/generator_components_pages.mjs
docs/package.json

fix https://github.com/FabienArcellier/streamsync/issues/51

fix: generation of documentation for components that fails on npm docs:build

---

src/ui/src/core_components/input/CoreSwitchInput.vue

fix: Switch input load bug

---

docs/docs/ai-module.md
src/streamsync/ai.py

- Fixed a bug with a empty string chunk
- Initialization from system prompt & list of messages 
- Message validation

chore: AI docs & fixes

---

docs/docs/ai-module.md
src/writer/ai.py

Added support for providing custom model parameter for all calls. Updated the docs to reflect that `system_prompt` and `history_import` are not named parameters.

fix: AI QOL updates

---

pytest.ini
tests/backend/test_ai.py
tests/conftest.py

Introduces a set of tests designed to validate the behavior of the components inside `writer.ai` module.
**Important: See module docstring for instructions on use.**

tests: AI module

---

src/ui/src/builder/BuilderFieldsPadding.vue
src/ui/src/builder/BuilderSelect.vue

fix https://github.com/FabienArcellier/streamsync/issues/62

chore: improve UI consistency (padding, content align)

---

docs/framework/release-notes-generator.mdx

Corrections and updates to the release notes generator tutorial ahead of the AI Studio workshop

Docs release notes updates

---

src/ui/src/core_components/content/CoreMetric.vue

[Screencast from 2024-07-25 21-40-27.webm](https://github.com/user-attachments/assets/087a346c-ad57-4177-bb6e-7a24af7d67f3)

feat(ui): allow empty name for `CoreMetric`. WF-38

---

src/ui/src/builder/BuilderHeader.vue
src/ui/src/builder/BuilderTreeBranch.vue
src/ui/src/builder/sharedStyles.css
src/ui/src/core_components/input/CoreCheckboxInput.vue
src/ui/src/core_components/input/CoreDateInput.vue
src/ui/src/core_components/input/CoreRadioInput.vue
src/ui/src/core_components/input/CoreRatingInput.vue
src/ui/src/core_components/input/CoreTimeInput.vue
src/ui/src/core_components/layout/CoreSidebar.vue
src/ui/src/renderer/sharedStyles.css
src/ui/src/wds/WdsDropdownInput.vue

Setup `cursor: pointer` for differents core components and also for differents parts of the application.

feat(ui): harmonize CSS cursors. WF-35

---

src/ui/src/components/core/layout/CoreHorizontalStack.vue

feat: horizontal stack should expose field Content alignment (V) - WF-56

---

src/writer/ai.py

Upgrade `palmyra-x-002-instruct` to `palmyra-x-003-instruct` as per WF-65

chore: bump completion default model

---

src/writer/core.py

fix: raw docstrings for `subscribe_mutation` & `parse_state_variable_expression`

---

.github/workflows/doc-notify.yml
alfred/github.py

feat: configure slack notification on documentation change

---

src/writer/ai.py

Improves response quality for LLM, ensures compliance with JSON Schema for parameter types.

fix: minor QOL updates for function tools

---

docs/framework/ai-module.mdx
src/writer/ai.py

Additionally includes a fix for LLM bug, and `max_tool_depth` parameter for `complete()` and `stream_complete()` (documentation updated accordingly)

fix: switch to `create_function_call` function due to lack of default `type`

---

package-lock.json
src/ui/.eslintrc.cjs
src/ui/package.json
src/ui/src/builder/BuilderComponentShortcuts.vue
src/ui/src/builder/BuilderFieldsPadding.vue
src/ui/src/builder/BuilderModal.vue
src/ui/src/builder/BuilderStateExplorerTreeBranch.vue
src/ui/src/components/core/content/CorePlotlyGraph.vue
src/ui/src/components/core/embed/CoreGoogleMaps.vue
src/ui/src/components/core/input/CoreSelectInput.vue
src/ui/src/components/core/other/CoreHtml.vue
src/ui/src/components/core/other/CorePagination.vue
src/ui/src/components/core/other/CoreRepeater.vue
src/ui/src/components/workflows/WorkflowsRoot.vue
src/ui/src/components/workflows/WorkflowsWorkflow.vue
src/ui/src/components/workflows/abstract/WorkflowsNode.vue
src/ui/src/components/workflows/base/WorkflowArrow.vue
src/ui/src/renderer/ComponentProxy.vue
src/ui/src/renderer/ComponentRenderer.vue

Get rid of all Eslint warning by hand and also bump `@typescript-eslint/eslint-plugin` to avoid incompatible Typescript version warning

chore(ui): clean Eslint error - WF-48

---

.github/workflows/ci-e2e.yml
.github/workflows/ci-macos.yml

Reverts writer/writer-framework#656

chore: Revert "chore: increase github action runner size"

---

src/writer/ai.py
tests/backend/test_ai.py

Enables usage of API `question` endpoint via `ask()` / `stream_ask()` methods.
Module-wide methods allow to use multiple instances of `Graph` class or multiple graph IDs to produce an answer; using methods on an instance of `Graph` class allows to query a single graph related to the instance.

feat: `question` endpoint usage for `writer.ai`

---

src/writer/ai.py

Provides autocompletion hints in IDE during function tool parameter definition.

chore: add a TypedDict to parameters definition

---

apps/hello/main.py
docs/framework/dataframe.mdx
src/ui/src/components/core/content/CoreDataframe.vue
src/writer/__init__.py
src/writer/core.py
src/writer/core_df.py
src/writer/ss_types.py
tests/backend/test_core.py

refact: rename EditableDataframe into EditableDataFrame

---

src/ui/public/components/progressbar.svg
src/ui/src/components/core/content/CoreProgressBar.vue

- The `CoreProgressBar` wrongly mentioned "Avatar"
- fix spelling mistakes
- add icon

fix(ui): fix `CoreProgressBar` description

---

docs/framework/ai-module.mdx
src/writer/ai.py
tests/backend/test_ai.py

Enables the use of `Tools` SDK resource and associated methods (`parse_pdf(...)`, `split(...)` and `comprehend_medical(...)` in Framework.

feat: `Tools` resource for AI module

---

docs/framework/frontend-scripts.mdx

Small PR - Commit c6591eff793db24ded0e99287c5f2ee22f87ecc7 moved `ui/src/core/index.ts` to be `src/ui/src/core/index.ts`. This PR adjusts sources to changes. Relevant page: https://dev.writer.com/framework/frontend-scripts

docs: update UI core index reference

---

docs/framework/seo.mdx

Refresh of SEO page to match the style of other docs and fix a few typos.

docs: SEO page improvements

---

src/writer/ai.py
src/writer/blocks/writerchat.py

Add a `description` field in `GraphTool` and use the tool's name in the Writer's chat workflow block as graph description.

feat(writer): include description in `GraphTool`

---

src/writer/ai/__init__.py

Extends the `writer.ai.apps.list(...)` to gather all apps available to user, similar to `writer.ai.list_graphs(...)`

chore: gather all available apps on `writer.ai.apps.list()`

---

src/ui/src/builder/BuilderApplicationSelect.vue
src/ui/src/builder/settings/BuilderFieldsWriterResourceId.vue
src/ui/src/builder/settings/BuilderSettingsProperties.vue
src/ui/src/writerTypes.ts
src/writer/app_runner.py
src/writer/blocks/foreach.py
src/writer/blocks/runworkflow.py
src/writer/blocks/writeraddtokg.py
src/writer/blocks/writernocodeapp.py

feat: implement writer application field - WF-167

---

src/ui/src/components/core/content/CoreJsonViewer.vue
src/ui/src/components/shared/SharedJsonViewer/SharedJsonViewerCollapsible.vue
src/ui/src/components/shared/SharedJsonViewer/SharedJsonViewerObject.vue
src/ui/src/components/shared/SharedJsonViewer/__snapshots__/SharedJsonViewer.spec.ts.snap

|---|----|
| ![image](https://github.com/user-attachments/assets/d501b531-867d-4b9e-ac1b-1562a4a0efef) | ![Screenshot From 2025-03-13 22-10-00](https://github.com/user-attachments/assets/c0ec7810-c43b-4d7e-abb3-c40b368296db) |
| ![image](https://github.com/user-attachments/assets/e0c3cd8d-32b4-4593-b72a-2eb6a1b4ac6c) | ![image](https://github.com/user-attachments/assets/d306b98b-3680-4345-849c-2542288e4fad) |
Following this [Figma](https://www.figma.com/design/EQMsUSTaMuo4TI03durC4R/Agent-Editor?node-id=87-134794&t=fezWTkKfgWgoCPsu-4)

fix(ui): improve design of JSON viewer - WF-216

---

src/ui/src/builder/panels/BuilderLogPanel.vue
src/ui/src/builder/panels/BuilderLogWorkflowExecution.vue
src/ui/src/builder/settings/BuilderSettings.vue
src/ui/src/builder/settings/BuilderSettingsHandlers.vue
src/ui/src/builder/settings/BuilderSettingsHandlersWorkflow.vue
src/ui/src/wds/WdsButtonLink.vue

- hide linked workflows in settings if no events
- introduce `WdsButtonLink` instead of custom link design in workflow links
- correct some spacing issues
- improve wordings

fix(ui): improve linked blueprint design - WF-223

---

src/ui/src/components/shared/SharedButtonCopyClipboard.vue
src/ui/src/components/shared/SharedControlBar.vue

- use WDS component for the "copy to JSON" button
- add a visual feedback that the content was copied

feat(ui): improve `SharedControlBar` UI - WF-230

---

src/writer/ai/__init__.py
tests/backend/test_ai.py

Adds tests for AI module that cover the new functionality in Writer SDK 2.0.

tests: AI module apps unit tests

---

src/ui/src/builder/BuilderApplicationSelect.vue
src/ui/src/builder/BuilderGraphSelect.vue
src/ui/src/builder/settings/BuilderFieldsWriterResourceId.vue
src/ui/src/writerTypes.ts
src/writer/app_runner.py

When the user setup the environment variable `WRITER_ORG_ID`, the "No code" workflow block and the "add to knowledge graph" settings panel will display a link to see the resource on Writer's AI studio.

feat: introduce external link to No-Code app / KG - WF-221

---

src/ui/src/builder/settings/BuilderFieldsComponentId.vue

fix(ui): include "root" node in component selector - WF-258

---

.devcontainer/devcontainer.json
src/ui/vite.config.ts
src/writer/autogen.py

- Change autogen model
- Devcontainer improvements

chore: Autogen change

---

src/ui/src/builder/BuilderApp.vue

Handle multi-selection when removing components. Before, we were removing only the first selected component.

fix(ui): remove all selected components - WF-263

---

src/ui/src/components/core/content/CoreLink.vue
src/ui/src/components/core/content/CoreMessage.vue
src/ui/src/components/core/content/CoreTags.vue
src/ui/src/components/core/content/CoreText.vue
src/ui/src/components/core/content/__snapshots__/CoreText.spec.ts.snap
src/ui/src/components/core/other/CoreButton.vue

|---|---|
| ![image](https://github.com/user-attachments/assets/21c178fc-d209-4e5a-b68a-8836b195f5c6) | ![image](https://github.com/user-attachments/assets/3468073f-1bb5-468b-8398-3c3d2e1cda2e) |

fix(ui): handle overflow for some UI components - WF-343

---

src/ui/src/builder/settings/BuilderFieldsComponentId.vue
src/writer/blocks/uieventtrigger.py

- update desc fro "UI trigger" default result field
- handle empty description in "Component field"

fix(ui): improve UI trigger block

---

src/writer/ai/__init__.py
src/writer/autogen.py
src/writer/blueprints.py
src/writer/core.py
src/writer/serve.py
tests/backend/test_ai.py

Enables session context for injection of `X-Agent-Token` header during API calls. Modifies the AI module to issue a new client with injected header on each attempt of client retrieval.

chore: session context for block execution

---

src/ui/src/components/blueprints/base/BlueprintToolbar.vue
src/ui/src/components/blueprints/base/BlueprintToolbarBlocksDropdown.vue
src/ui/src/wds/WdsButton.vue
src/ui/src/wds/WdsButtonSplit.vue
tests/e2e/tests/blueprints.spec.ts

Refactor `BlueprintToolbarButtons` into a generic component `WdsButtonSplit`

feat(ui): introduce `WdsButtonSplit` - WF-360

---

package-lock.json
src/ui/package.json
src/ui/src/builder/BuilderHeader.spec.ts
src/ui/src/components/core/other/CoreReuse.vue

fixes https://github.com/writer/writer-framework/security/dependabot/61

chore(ui): bump vitest version

---

src/writer/blocks/__init__.py
src/writer/blocks/writerfileapi.py
tests/backend/blocks/test_writerfileapi.py

Adds a `WriterUploadFile` ("Add files to Writer Cloud") block.

feat: `WriterUploadFile` block

---

src/writer/blocks/__init__.py
src/writer/blocks/writerparsepdf.py
tests/backend/blocks/test_writerparsepdf.py

A block that accepts a PDF file and executes a request to the API PDF parser tool.

feat: Writer Parse PDF block

---

src/ui/src/builder/BuilderHeader.vue
src/ui/src/composables/useApplicationCloud.ts

https://github.com/user-attachments/assets/50a61844-729c-4f54-bf74-b1451262f6db

feat(ui): add link to AI studio in the header - WF-373

---

src/ui/src/builder/BuilderApp.vue
src/ui/src/builder/useComponentAction.spec.ts
src/ui/src/builder/useComponentActions.ts
src/ui/src/renderer/ComponentProxy.vue

https://github.com/user-attachments/assets/56fb072b-458d-44e8-9a93-a3f31e9bc996

feat(ui): implement component selection shortcurts - WF-326

---

src/ui/src/builder/BuilderModelSelect.vue
src/ui/src/builder/settings/BuilderFieldsWriterResourceId.vue
src/ui/src/builder/settings/BuilderSettingsProperties.vue
src/ui/src/writerTypes.ts
src/writer/app_runner.py
src/writer/blocks/writercompletion.py
src/writer/blocks/writerinitchat.py
src/writer/blocks/writertoolcalling.py

New `Model Id` field that enables a dropdown selection of Writer Palmyra LLMs for relevant blocks.

feat: model selection field

---

src/writer/blueprints.py

https://writerai.atlassian.net/browse/WF-298

feat: run workflow block if at least one dependency is fulfilled - WF-298

---

src/ui/src/builder/settings/BuilderFieldsWriterResourceId.vue
src/writer/app_runner.py

Upon agent selection in `AI Studio Agent` block, populates the `App Inputs` with input data provided by API.

chore: populate `appInputs` upon agent selection
